name: nerf_factory
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.12
  - requests=2.27.1
  - tqdm=4.62.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pip:
      - pytorch-lightning==1.7.4
      - opencv-python==4.6.0.66
      - gin-config==0.5.0
      - gdown==4.5.1
      - ninja==1.10.2.3
#      - functorch==0.2.0
      - functorch==0.1.1
      - torch-efficient-distloss==0.1.3
      - torch-scatter==2.0.9
      - configargparse==1.5.3
      - scikit-image==0.19.3
      - tensorboard==2.10.0
      - imageio-ffmpeg==0.4.7
      - piqa==1.2.2
      - wandb==0.13.2
      - imageio==2.21.2

        # cuda version에 맞춰서 torch, torchvision, cudatoolkit, torch-scatter 깔아야 한다.
